spring.application.name=bff-agendador-tarefas

user.url=${USUARIO_URL:http://localhost:8080/usuario}
tasks-scheduler.url=${AGENDADOR_TAREFAS_URL:http://localhost:8081/tarefas}
notification.url=${NOTIFICACAO_URL:http://localhost:8082/email}

server.port=8083

cron.hour=0 0/5 * * * ?

user.email=admin@admin.com
user.password=1234